# MinIO 配置
minio:
  url: "http://192.168.31.175:9000"
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint:
    enable: true

# 文件大小限制
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 500MB